server:
  port: 8765

spring:
  application:
    name: admin-client
#  security:
#    user:
#      name: "client"
#      password: "client"
  boot:
    admin:
      client:
        url: http://localhost:8766	#server端地址
        username: admin	#对应server端的账号密码，不配置就监控不到这个client。
        password: password
        instance:
          service-base-url: http://localhost:8765	#client地址，

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
      health:
        show-details: ALWAYS

logging:
  file: var/log/sample-boot-application.log
#  pattern:
#    file: clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID}){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx

#eureka:
#  instance:
#    leaseRenewalIntervalInSeconds: 10
#    health-check-url-path: /actuator/health
#    prefer-ip-address: true
#    metadata-map:
#      user.name:  ${spring.security.user.name}
#      user.password:  ${spring.security.user.password}
#  client:
#    registryFetchIntervalSeconds: 5
#    service-url:
#      defaultZone: http://admin:password@114.55.58.53:8761/eureka/

info:
  version: @project.version@
  groupId: @project.groupId@
  artifactId: @project.artifactId@

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
